[package]
name = "hf_tokenizers"
version = "1.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[build-dependencies]
csbindgen = "1.9.3"

[dependencies]
tokenizers = "0.20.0"
once_cell = "1.19.0"
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "macro-diagnostics"] }

[build]
target = "x86_64-pc-windows-gnullvm"

[build.aarch64-pc-windows-gnullvm]
linker = "aarch64-w64-mingw32-clang++"
ar = "aarch64-w64-mingw32-llvm-ar"

[build.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar = "aarch64-linux-gnu-ar"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
