[package]
name = "hf_tokenizers"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[build-dependencies]
csbindgen = "1.9.1"

[dependencies]
tokenizers = "0.19.1"
once_cell = "1.19.0"
