name: Build (Windows-x64)

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build (Rust runtime library)
      shell: pwsh
      run: |
        .\build_rust.ps1
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: |
    #       6.0.x
    #       7.0.x
    #       8.0.x
    - name: Build (Dotnet library)
      shell: pwsh
      run: |
        .\build_dotnet.ps1
    - name: 'Artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: Built packages
        path: |
          nuget/win-x64/Tokenizers.DotNet.runtime.win.*.nupkg
          nuget/Tokenizers.DotNet.*.nupkg
